### ISSUE TITLE
Could not build with php 8

### ISSUE THREAD

**Issue by IndexOutOfMJ** [stephan-strate/php-music-brainz-api#41]
Hey there,

I'm using php 8.0, if i try to run the composer command I'm getting the following error:

Could not find a version of package stephan-strate/php-music-brainz-api matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

I tried to run 

composer config minimum-stability dev

and 

composer config prefer-stable true

and

composer require guzzlehttp/guzzle:^7.2 http-interop/http-factory-guzzle:^1.0 stephan-strate/php-music-brainz-api:v0.0.1-alpha

as well as

composer require guzzlehttp/guzzle:^7.2 http-interop/http-factory-guzzle:^1.0 stephan-strate/php-music-brainz-api:dev-master

the last two commands gaved me this error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires stephan-strate/php-music-brainz-api v0.0.1-alpha -> satisfiable by stephan-strate/php-music-brainz-api[v0.0.1-alpha].
    - stephan-strate/php-music-brainz-api v0.0.1-alpha requires php-http/client-implementation ^1.0 -> could not be found in any version, but the following packages provide it:
      - symfony/http-client Provides powerful methods to fetch HTTP resources synchronously or asynchronously
      - php-http/guzzle6-adapter Guzzle 6 HTTP Adapter
      - symfony/symfony The Symfony PHP framework
      - php-http/curl-client PSR-18 and HTTPlug Async client with cURL
      - php-http/guzzle7-adapter Guzzle 7 HTTP Adapter
      - kriswallsmith/buzz Lightweight HTTP client
      - php-http/mock-client Mock HTTP client
      - php-http/socket-client Socket client for PHP-HTTP
      - php-http/guzzle5-adapter Guzzle 5 HTTP Adapter
      - voku/httpful A Readable, Chainable, REST friendly, PHP HTTP Client
      - php-http/react-adapter React HTTP Adapter
      - code-tool/curl-client cURL client
      - php-http/buzz-adapter Buzz HTTP Adapter
      - juststeveking/http-slim A slim psr compliant http client to provide better interoperability.
      - jorge-matricali/http-client A wrapper of libcurl that implements PSR-7 HTTP message interface.
      - php-http/cakephp-adapter Cake adapter for PHP-HTTP
      - swisnl/php-http-fixture-client Fixture client for PHP-HTTP
      - windwalker/http Windwalker Http package
      - windwalker/framework The next generation PHP framework.
      - neur0toxine/pock PSR-18 compatible HTTP mock library
      ... and 34 more.
      Consider requiring one of these to satisfy the php-http/client-implementation requirement.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by stephan-strate** [comment]
First of all: Sorry for not answering. This issue got lost in my inbox somehow.

Even if it is too late right now, I am trying to help you at this point. This issue is not really related to php version. The documentation in the README.md was just wrong (I updated it btw).

The library does not implement a custom http client nor ships an existing one. It is decoupled from it using HTTPlug. HTTPlug offers some http client implementation, which you can find [here](https://packagist.org/providers/php-http/client-implementation). One of these needs to be installed with the library. Thats what `stephan-strate/php-music-brainz-api v0.0.1-alpha requires php-http/client-implementation ^1.0 -> could not be found in any version, but the following packages provide it` says. The README.md is now updated to install `php-http/guzzle7-adapter:^1.0` and therefore guzzle7.

Hope this helps. Let me know if this solves your problems.
